language: bash
services:
- docker
before_install:
- docker build -t m0rf30/arch-yay .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  global:
  - secure: DQU7z+c5cnmBK/yfbXnb7RAy67dtCQo/gQOAVsAC+uvgkWanESHvIZn5DZ3+lt5B4/Dt3OFSsLrVwYFlTe/ed8eaV167tDtY3yRLp7h2vpxNebbNSpBxdYyWE9JN27M/kd936PzG8iIFkGKquQO9LCzM7S7nlArfXbbQkCswEQGTyV8IE0eR1rqZKpb8c1d01mshuhyAoO8Vk5Szzd23Tb2p07spXrhde353KcY69rAa6s2h+vAjea/SX+4JOuGfyep+jUtY05LJCRgFg7YXLnguiOCawzZIQjdQ3ELzHDoql6nJc2PS67IWMHN8TLPZ26Gmuv0h+VZ5moJ9SI9TXszWCxB1YEVwRyflIpXYZSH8PaBFzM309otaYnKZjvom+XZN/4kMMhXAOtzK/N2TmjJ/RVKiSj3c5ohMDf0CWlKqC+dJdjjCNzvnWRD4Mf4H1aaLCntrN77reJSWiiLxzlRSBhdp6uLWSd2qSKotMx7nkb8v7QBFbGQ4932frk4xOiPdAw5GibwlihEBkMBP6MMW64RYXIaFYR1Ck2ffaS5CKsNxP80RBVru/VecqxfxkidrnIGcmRcHJt+9yb5uCrTF7ONlGMqn4TEe48+WGS9gyXfJVT747g2gN+eLmLRt3Yjep9QlYQ5cklF46cK6B8TO+ImiWu39gTsTLvciitU=
  - secure: QR70XZcgFevvoTeEE7D1bvsladRRPJd9P4ENGNRJE6nskjilT5SE3Vu5kvNUABUwlXij5AvFyoUU+QMhkToLP6w0UZPvpBhRw3xhXU554uKvILYWoOAAaQCPYSGCVdPe/5g+N/QiU3F8N7yq9/JyL5JeVv6GVyTY+mr5aQBvOexkQ5Qa11nQZFaZdIoilwUuHSGozU3WfskKzD7r+aMnCVKra8S0SIIc7s1kA4NMb5e6h9r9Ium9s7FYVogdZjSVuffqex6zbC2iE0xTxeh1S40JS+HcM08Yo6xfqocJvKLbWzaAAzMRvL31sFiKgxboh30QfGht7PdTU55l5+ajdHcHxnVYwG7dIG2V5heH6vi36j+aJKGNh61I68eUACTSJe9WQYcRawhMzDG7+dLyfyDGg1mmBL2CDG4q8MQESoyQSLeC1eHmbBZkZ60hSZwd8QwEjRljfA7VKJdFQgOHcADpy6hLzz3Dw4YlB5RibyR8dnCxmzhH/FeWZ2Wsd5vcpPcCqq7fejGfbd2jLdfv/rcNd9mWO7N3VodUKGgzVHOlTuTUfL5pY56v3sZRG+BWrFAPWPf4YvM0MWno4LtGLtWl1xxi082e8+FTsy8jEevs+koP0XCEcicG/Fjj5fULu2RrgLibL23HEeOBMSFZ75RimCwV1l7zPRELLhk3qPg=
