language: bash

services:
- docker

before_install:
- docker build -t m0rf30/arch-yay .

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master

env:
  global:
  - secure: DnTQPLlIP49Ya2sn7PCoa2y67q0b2RY7ppRXSqcADpI5CpGfRm+WBwDZDA53J2CufahuABRCAugzCNAyE+T91F5I/GLH0qI4P/An3wMJZmShEQG+Z9OJMOmdM6BtfO21h2MUvRqEucHyASL6xtER7fXbBzXzZETrU2Au78zJzH/jBEEC9EQDbHB6L7HnvgrqGQy0msS9P43SWR2G9T6UZp6DL8sQgsSOuAykW7wjK7dNfpXlMOif7yUnGNqalS3ksjC1dm86hzyHrhFCyuqYqfdOpH+ee5AmiksbUzh0TObHeBxFCjoW3TT98kkmJdvfrkKXSfphPJkL2BS7OwbEiI+HsowtRle4QRPfwtINuyIWjtXGLB8wWJZniZh5+U3npcOgE2Njpx0EyE5ObDY8Y7DpRAgMZ/Du3BGrX9jGy3bJobFvBdyx15G6mDF4S2L1Pk6yjve+4er/f2hA3MSnnSlCpJliNy1Cgsyi8S3DEiXqdRw5mcZxHm/bnwCjq7ghWBkvyoL3X2MW4Z6cTBok3V2FAfcsk1iv5Pr6t164/DxWr9x53wJtFAGY2YZnlxtJTRYmsqTAmRoZH/pT95tOWS3JzTnxSDF9/AgnjqjJFqZiS2GZ18gwZGJ9jIzykAlcqXcMeR4oPoCMlhWAj5o0IdKKcWNGAfUZsNsmjW/y3fw=
  - secure: qZrszCI+ihY3YkYA7lD7kiJJGqeG+9kWgF1TrDMfNg1uA9r9VaxFWkxkhWJdFBXsLe3B/P4f8zwF8ompjJXzboaMDEQogFcHPv4At5dwoxvQMdBYuXLDyamPk0p9Wkn7zbQkwLUo2Cvs8S6m/748EbR/nyMfNhFw3BUVWwcQz+Br9sw6IiMERQeRF47pF7OTfs2B3fIwtLL0QCoB+WpWgz5cz4h0CGJhjrK3eGLKBI5H6Bx1bocbcqNJ8dCUZUYCv8HXHPuJDeWe0iVN+PCgVsqL3H/lJzrArILuE6O+SBrPUfbvlfpYYJiphJ1dNXzgXib8sAKkCX+5+WYuG37kLrXG0TbkpYn451Gs1Bqcs5kwJ8Z3uM1RTvkJTOFk8pPhZeao20PU39xVwrPC5gZgGQvNYPT9dRyMsDIJVIf0FoYb5IFjOAHIwZ+gxidpabT3SqB7TwOLkSbwDVzKxnxEW2yGPc/k2waqRmaqjowdL8ZhiM3qenWOEzaM+Sl4PZA/rfcX2OhH/HxMhUtXC8O3CqDFolBBtpgO+Pr6j2q4mC2gl4wqWO0G/U8G2DDNuKH7i2RbvByadZb5ha3X9oKN1P6rT6102vY8yr+jvXARHVVWMTHGSYxK9LAiRL+J0qOJe03TCNsBXNMaIy20+niX/Q9txjk53Y7dDSaCe+6jH2A=
