language: bash

services:
- docker

before_install:
- docker build -t m0rf30/arch-yay .

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master

env:
  global:
  - secure: GYfQ+HwQnVEyvxutJ/ayRE2sTypw0FYqYF9QcnO+Bfeijx7M4T0QR+/hHG3q3FIN+oAoVznHa2mAn52EHn8D5Z6sfLaFKmIQTp8/H5sZKXXgkL10I2hYGjUhCykBEI40MLfVq+cequt+cByoLjMpcgZKyrvcifpMWC4QY3tT2ReXj4zYSrcRfjcquuJjdJCooLUXudPputi5adBNjUQo0EQnVCpHEB3X+0w1cbX3uIr2O8xlxb4l8GXfLTF4HdfHHbySRD3SiCFiOjWZeHEQAuIyk0Zj45O2kJW3+aGFSEXomeLpATamOIeK8g+RdEc1CfvmFMawIbGj1h3zUDlvsZUMD1niGy6i+15rBdrD9Q54tpPfWZ91iLKu4wGr8EY8qT6YAa5MadbIw60yhPf7TYIS0bEF2VzW+DXp5qQh1IPW0zj5uFGAG7xoCbILqjVkxl2rsMnJWfRcC5j2jqXTWRnMsxjp3002CSqHfqQm+NucbZCFuV7nOHT2wPPHriyf8VwvVc5C8Q89tTX/+fAQaAr4gsRtZY2j/DfE8JQDc5GA+ryFWb96S03dyXMA91qAG2ZyI5NbQ2D9R+Cxe87LftdDG+lj8aMv6kfwdzSTYWnsRGDhBj6KSqm1Ci/3o71r5vNvStX0ZojSr4N5pP+JoICZP+JHwY3n4hIjMmLNhfo=
  - secure: LtR/mwfrpNDpy8HNsLFJCDb1Q4fjKZ1eS7uQws7YoJsmDtQwwRHEtnj+L9qfF7/jwP1cRYmSWA6vZD+i0O319YCEPJtSRr3tqkGIsyf0EvUcW85bsl62s4srR6uuqIqjJt83G5dG97pZDL4yVuhJpdWh180GA9zvraXlItNlpi6bIztqJjB6dvXdgzgQegrUW9CRPNTdLGtbEcxU9EA8upWnOz3SLciYP4ZAZ1Q0o8NajL8Chu/U5JPSRHe/CSp+aGRJJ/sGpHRhgAjBvi7GPwW/Hb7yEaBDYJE+VD3yfmkXpl6oeYpm6097XwPydx+WH3keei6fVz3bkgysEEmJykxq9U44rYjiV3m+/XcTrp01nh/91Nz0twm09aw6tot+hGVXtdt2IZrL9WIY7DZ7pbZi4oN+BZbr74ukz5JlTuvuKrvzTuaK9YC46O0yoIU+ctQ5NfdT+lUwJxTrXZrLxg4Hrs5nQ27xpHYg54HvySCnSBEKgDYoISOK0VwAl2I9pD/psVqVuEL5NBI2SGQ1FNucV428YfTYEy9DWjEETWTXyz6r6ThRgfy5Npm7PV9K17zfCUGtafPhvNMLAWyy/M/Djxsa6EyAQ08s9EW5PjfzHhXo/VN545g/BD5TSNTK08mxJpiFbcn9cGBuk6/dnd9DinWOslmvunaiqGbsQqA=
