language: bash
services:
- docker
before_install:
- docker build -t m0rf30/arch-yay .

env:
  global:
  - secure: NWbJXg0ELP8Hj5OCCrJ6r6aWx2KrfSTW6j1QHwm/xZ7SWyRH7RBDf/bXJKufsNV8HvXf6Y0RfcYrBQNFZF4/j7OhTKK37rgTo91hd4MZH6lA+68EsOgws+vZQrDfSrllnFi0gwyqnrFNpf06MU2oZ9rmKUHRw/X4gac0uuXT53o3v8q/PtDIDn8IRDYvR4GUoSjBLQQByLzWE6/O6MQe+eRTWKQihMkHRAMYcjDMqu0KrFbEumh7C0/XGHH9hI/frzO6Hl1K5mkPFALNkW1wic+DH8pO2WmWNWRGV3o2DasxfTW9gnoFGVND2LbkH7Bhjy6/qWgh+KvWGQRh0MFo7nJ6dHVlG+ZKb5jRhTtFpOwB5dUss4Xgl89/hS74VoWN7Jv78trdKoOWIT+NZy265MSGL8lBblIdOxo0LqC1QDOmoZ2xJ1Mgix+iQLhFjezgisI0YSOYPrtCpzuhYoULJPhpFEuTPZMo3HDNa9X87G6S4LbpUcB1nEuOb+g0Md14zVUnpUnBnEw341O60IhlIsk5kUntVW3sbcsKxt93ouzR+n9xgXuH6ZSgYLXUY50hvJXdyu3cmTKabvReBaFyLit9iC6GgxTx1owpT+3aGhgIfkbwlBegEsnncld+/yP5RU8qkHGxuAvhh+TtQunH9s/wZ6I24ZtUty4G/nWRMK0=
  - secure: LUkeRTJSOhZJqJyBSqSERU6bFSSYQTAPztH7md9bYutcaMgdybqUGPa1yqqIa2hjrxKeyNquGZ/thdeSulszanjpgLVxX7fkeYknYI6C2vu8t5T60TTZ1JcygXrdpG6C15aWQWf7SirT1r7Zlu2EYfNKRrluRqG32Ab+nW5iVE/BDihnkEZ2BfulOY1SvMuztPCkGz+9jGqNBHqiotcya4hokynUFRQgZYDEe+Tujf+Eab8xZt+lj5tchfSMQp9QXqutLDieYqVhd9ETNSQFkfhvYITLVFKFhfprTVLBHOuh3/ySZ1RlsVa7D/Uv8qUDOHK/D99VKBxwoF8LxgBQhlPP7xvaBM4qLwSihdlDmEYz1WNLx73X/q+Wi0SdkoZkTAWXkdLy5Qv/A9AHc7lLx4WkncNd8Cmtd5+4zV09oQ7i5C5t1izVxILA8RbKGtalrnh0i6hUeF38iynE1HWWicHD2UAcBrA9Xl6kaYYmH3kBFZJYkv0JZlu8hblLwu0+352rUbbOtUSx0Gw+EbTbjOqEDENGuknA9AnsquJXUG/Tfl053CyAWYCG8pO3ZHjNK2yly/DHEMRlKpSYahLkDrEADpEZt2Ny1gisdbqv2/qdccCVEsy+sub4jW+sv2YDU531ed3NgV3SmzD5VHfLyN45cMbCH7bY1lp20eUTj9Y=

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master
