name: Docker Image CI

on:
  push:
    branches:
      - main
  schedule:
      - cron: "0 6 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: m0rf30/arch-yay*
          labels: |
            maintainer=M0Rf30
            org.opencontainers.image.title=arch-yay
            org.opencontainers.image.description=Arch Linux Image with AUR support through yay
            org.opencontainers.image.vendor=M0Rf30
          tags: |
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            m0rf30/arch-yay:latest
            ghcr.io/m0rf30/arch-yay:latest
          file: Dockerfile

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "m0rf30/arch-yay:latest"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
